# Generated by Django 4.2.19 on 2025-03-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about_alter_post_updated_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
